# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c08d3b39375b1fccefdb821f483b7532564606709c9e4ea42efaf5559d727a2f7cb915a5feceb6412fdcb56058abbca7b6b69e82cfd23b18eb2aecdcf2007fb1

test:
  secret_key_base: 26b697bcbe13c6d6bf5134374ae5c0874af412b731a9fec576bdae95a989e9f771c1ff3517475f427384f9e119f7bda1a73fae765250fe4df4c6d9d1e8a245f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
